# PyTorch Education


I will be taching myself how to use the `PyTorch` library in Python and how I can use this library instead of tensorflow. I think `PyTorch` would be better for me to practice Python rather than tensor flow because of how `torch` makes use of object oriented programming while creating models. I will be learning how to deal with tensors which are the backbone of `PyTorch`.

# **:)**

In [1]:
# importing libraries

import torch
import numpy as np

In [6]:
# making tensors
# tensors are arrays of numbers that are usually

tensor_1 = torch.tensor([1,2,3])
print(f"First Tensor: {tensor_1}")

First Tensor: tensor([1, 2, 3])


In [7]:
# you can use numpy arrays and make them into torch tnesors

array_1 = np.array([1,2,3])
tensor_2 = torch.tensor(array_1)
print(f"Tensor with NumPy: {tensor_2}")

Tensor with NumPy: tensor([1, 2, 3], dtype=torch.int32)


In [18]:
# Empty Tensors, Zero Tensors, and Ones Tensors

empty_tensor = torch.empty(3)
print(empty_tensor)

zero_tensor = torch.zeros(2,3)
print(zero_tensor)

ones_tensor = torch.ones(2,3)
print(ones_tensor)

tensor([0., nan, 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
# You can make random tensors

rand_tensor = torch.rand(3,3)
print(rand_tensor)

tensor([[0.5099, 0.5462, 0.7304],
        [0.4628, 0.6690, 0.6679],
        [0.2311, 0.3115, 0.2178]])


In [ ]:
# Arrange Tensor

